[2025-01-23T04:10:05.789+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: All_Layer.clean_review manual__2025-01-23T04:04:38.366035+00:00 [queued]>
[2025-01-23T04:10:05.809+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: All_Layer.clean_review manual__2025-01-23T04:04:38.366035+00:00 [queued]>
[2025-01-23T04:10:05.810+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-23T04:10:05.836+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): clean_review> on 2025-01-23 04:04:38.366035+00:00
[2025-01-23T04:10:05.843+0000] {standard_task_runner.py:57} INFO - Started process 12018 to run task
[2025-01-23T04:10:05.849+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'All_Layer', 'clean_review', 'manual__2025-01-23T04:04:38.366035+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/All_Offi.py', '--cfg-path', '/tmp/tmpiwfvbwtb']
[2025-01-23T04:10:05.854+0000] {standard_task_runner.py:85} INFO - Job 82: Subtask clean_review
[2025-01-23T04:10:05.986+0000] {task_command.py:416} INFO - Running <TaskInstance: All_Layer.clean_review manual__2025-01-23T04:04:38.366035+00:00 [running]> on host 73fc507ad5e4
[2025-01-23T04:10:06.174+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='All_Layer' AIRFLOW_CTX_TASK_ID='clean_review' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T04:04:38.366035+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-23T04:04:38.366035+00:00'
[2025-01-23T04:10:06.199+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-01-23T04:10:06.204+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_review.py s3a://lakehouse/bronze/review.parquet s3a://lakehouse/silver/review
[2025-01-23T04:10:06.554+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-01-23T04:10:11.200+0000] {spark_submit.py:579} INFO - 25/01/23 04:10:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-23T04:10:12.646+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/processing_review.py", line 26
[2025-01-23T04:10:12.647+0000] {spark_submit.py:579} INFO - .getOrCreate()
[2025-01-23T04:10:12.651+0000] {spark_submit.py:579} INFO - IndentationError: unexpected indent
[2025-01-23T04:10:12.670+0000] {spark_submit.py:579} INFO - 25/01/23 04:10:12 INFO ShutdownHookManager: Shutdown hook called
[2025-01-23T04:10:12.672+0000] {spark_submit.py:579} INFO - 25/01/23 04:10:12 INFO ShutdownHookManager: Deleting directory /tmp/spark-615ee3d4-36f5-4b83-a3bb-70b948de20a1
[2025-01-23T04:10:12.724+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_review.py s3a://lakehouse/bronze/review.parquet s3a://lakehouse/silver/review. Error code is: 1.
[2025-01-23T04:10:12.730+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=All_Layer, task_id=clean_review, execution_date=20250123T040438, start_date=20250123T041005, end_date=20250123T041012
[2025-01-23T04:10:12.752+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 82 for task clean_review (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-bundle-1.12.262.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_review.py s3a://lakehouse/bronze/review.parquet s3a://lakehouse/silver/review. Error code is: 1.; 12018)
[2025-01-23T04:10:12.773+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-23T04:10:12.799+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
