[2024-10-04T01:50:31.732+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_layer_processing.bronze_keywords manual__2024-10-04T01:50:30.321120+00:00 [queued]>
[2024-10-04T01:50:31.743+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_layer_processing.bronze_keywords manual__2024-10-04T01:50:30.321120+00:00 [queued]>
[2024-10-04T01:50:31.743+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-04T01:50:31.761+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): bronze_keywords> on 2024-10-04 01:50:30.321120+00:00
[2024-10-04T01:50:31.769+0000] {standard_task_runner.py:57} INFO - Started process 1094 to run task
[2024-10-04T01:50:31.772+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bronze_layer_processing', 'bronze_keywords', 'manual__2024-10-04T01:50:30.321120+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/bronze_layer.py', '--cfg-path', '/tmp/tmp0jptw2x4']
[2024-10-04T01:50:31.776+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask bronze_keywords
[2024-10-04T01:50:31.828+0000] {task_command.py:415} INFO - Running <TaskInstance: bronze_layer_processing.bronze_keywords manual__2024-10-04T01:50:30.321120+00:00 [running]> on host 928e276d789d
[2024-10-04T01:50:31.895+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bronze_layer_processing' AIRFLOW_CTX_TASK_ID='bronze_keywords' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T01:50:30.321120+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T01:50:30.321120+00:00'
[2024-10-04T01:50:32.155+0000] {logging_mixin.py:151} INFO - Error getting data from MinIO: Unable to locate credentials
[2024-10-04T01:50:32.156+0000] {logging_mixin.py:151} INFO - Error in bronze_keywords task: Unable to locate credentials
[2024-10-04T01:50:32.157+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bronze_layer.py", line 53, in bronze_keywords
    raise e
  File "/opt/airflow/dags/bronze_layer.py", line 48, in bronze_keywords
    df = get_data_from_raw('keywords')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bronze_layer.py", line 32, in get_data_from_raw
    raise e
  File "/opt/airflow/dags/bronze_layer.py", line 27, in get_data_from_raw
    response = client.get_object(Bucket="lakehouse", Key=f'raw/{name}.csv')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 963, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 986, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2024-10-04T01:50:32.172+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=bronze_layer_processing, task_id=bronze_keywords, execution_date=20241004T015030, start_date=20241004T015031, end_date=20241004T015032
[2024-10-04T01:50:32.185+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task bronze_keywords (Unable to locate credentials; 1094)
[2024-10-04T01:50:32.226+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-04T01:50:32.250+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
