[2024-10-03T18:14:28.209+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2024-10-03T18:14:25.958923+00:00 [queued]>
[2024-10-03T18:14:28.219+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2024-10-03T18:14:25.958923+00:00 [queued]>
[2024-10-03T18:14:28.220+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-10-03T18:14:28.233+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-10-03 18:14:25.958923+00:00
[2024-10-03T18:14:28.239+0000] {standard_task_runner.py:57} INFO - Started process 256 to run task
[2024-10-03T18:14:28.242+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'manual__2024-10-03T18:14:25.958923+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpngbt45bh']
[2024-10-03T18:14:28.244+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask python_job
[2024-10-03T18:14:28.290+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job manual__2024-10-03T18:14:25.958923+00:00 [running]> on host 2b69184a959f
[2024-10-03T18:14:28.358+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T18:14:25.958923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T18:14:25.958923+00:00'
[2024-10-03T18:14:28.367+0000] {spark_submit.py:273} INFO - Could not load connection string spark-conn, defaulting to yarn
[2024-10-03T18:14:28.368+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py
[2024-10-03T18:14:28.457+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-10-03T18:14:30.694+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-10-03T18:14:30.695+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2024-10-03T18:14:30.696+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2024-10-03T18:14:30.696+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2024-10-03T18:14:30.697+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2024-10-03T18:14:30.697+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2024-10-03T18:14:30.698+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2024-10-03T18:14:30.699+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2024-10-03T18:14:30.699+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2024-10-03T18:14:30.700+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2024-10-03T18:14:30.700+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-10-03T18:14:30.730+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.
[2024-10-03T18:14:30.735+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20241003T181425, start_date=20241003T181428, end_date=20241003T181430
[2024-10-03T18:14:30.746+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task python_job (Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.; 256)
[2024-10-03T18:14:30.784+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-03T18:14:30.808+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
