[2024-10-04T00:59:26.458+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_layer_processing.bronze_keywords scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T00:59:26.468+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_layer_processing.bronze_keywords scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T00:59:26.469+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-04T00:59:26.484+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): bronze_keywords> on 2024-10-03 00:00:00+00:00
[2024-10-04T00:59:26.493+0000] {standard_task_runner.py:57} INFO - Started process 545 to run task
[2024-10-04T00:59:26.495+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bronze_layer_processing', 'bronze_keywords', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/bronze_layer.py', '--cfg-path', '/tmp/tmpadzqxbnx']
[2024-10-04T00:59:26.498+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask bronze_keywords
[2024-10-04T00:59:26.549+0000] {task_command.py:415} INFO - Running <TaskInstance: bronze_layer_processing.bronze_keywords scheduled__2024-10-03T00:00:00+00:00 [running]> on host b17a734dfca2
[2024-10-04T00:59:26.621+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bronze_layer_processing' AIRFLOW_CTX_TASK_ID='bronze_keywords' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T00:59:27.291+0000] {logging_mixin.py:151} INFO - Table extracted with shape: (46419, 2)
[2024-10-04T00:59:27.568+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-10-04T00:59:27.580+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=bronze_layer_processing, task_id=bronze_keywords, execution_date=20241003T000000, start_date=20241004T005926, end_date=20241004T005927
[2024-10-04T00:59:27.632+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-10-04T00:59:27.658+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T01:36:18.348+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=bronze_layer_processing/run_id=scheduled__2024-10-03T00:00:00+00:00/task_id=bronze_keywords permission to 509
[2024-10-04T01:36:18.350+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=bronze_layer_processing/run_id=scheduled__2024-10-03T00:00:00+00:00/task_id=bronze_keywords permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bronze_layer_processing/run_id=scheduled__2024-10-03T00:00:00+00:00/task_id=bronze_keywords'
[2024-10-04T01:36:18.382+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=bronze_layer_processing/run_id=scheduled__2024-10-03T00:00:00+00:00/task_id=bronze_keywords permission to 509
[2024-10-04T01:36:18.382+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=bronze_layer_processing/run_id=scheduled__2024-10-03T00:00:00+00:00/task_id=bronze_keywords permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bronze_layer_processing/run_id=scheduled__2024-10-03T00:00:00+00:00/task_id=bronze_keywords'
[2024-10-04T01:36:18.424+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_layer_processing.bronze_keywords scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T01:36:18.432+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_layer_processing.bronze_keywords scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T01:36:18.433+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-10-04T01:36:18.447+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): bronze_keywords> on 2024-10-03 00:00:00+00:00
[2024-10-04T01:36:18.452+0000] {standard_task_runner.py:57} INFO - Started process 603 to run task
[2024-10-04T01:36:18.458+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bronze_layer_processing', 'bronze_keywords', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/bronze_layer.py', '--cfg-path', '/tmp/tmpm70un41r']
[2024-10-04T01:36:18.468+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask bronze_keywords
[2024-10-04T01:36:18.532+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=bronze_layer_processing/run_id=scheduled__2024-10-03T00:00:00+00:00/task_id=bronze_keywords permission to 509
[2024-10-04T01:36:18.533+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=bronze_layer_processing/run_id=scheduled__2024-10-03T00:00:00+00:00/task_id=bronze_keywords permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=bronze_layer_processing/run_id=scheduled__2024-10-03T00:00:00+00:00/task_id=bronze_keywords'
[2024-10-04T01:36:18.534+0000] {task_command.py:415} INFO - Running <TaskInstance: bronze_layer_processing.bronze_keywords scheduled__2024-10-03T00:00:00+00:00 [running]> on host 928e276d789d
[2024-10-04T01:36:18.615+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bronze_layer_processing' AIRFLOW_CTX_TASK_ID='bronze_keywords' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T01:36:19.373+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bronze_layer.py", line 38, in bronze_keywords
    df = get_data_from_raw('keywords')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bronze_layer.py", line 25, in get_data_from_raw
    response = client.get_object(Bucket="lakehouse", Key=f'raw/{name}.csv')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the GetObject operation: The Access Key Id you provided does not exist in our records.
[2024-10-04T01:36:19.392+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=bronze_layer_processing, task_id=bronze_keywords, execution_date=20241003T000000, start_date=20241004T013618, end_date=20241004T013619
[2024-10-04T01:36:19.409+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task bronze_keywords (An error occurred (InvalidAccessKeyId) when calling the GetObject operation: The Access Key Id you provided does not exist in our records.; 603)
[2024-10-04T01:36:19.434+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-04T01:36:19.455+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
