[2025-01-23T03:25:03.979+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Silver_Layer.clean_keyword scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-23T03:25:03.989+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Silver_Layer.clean_keyword scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-23T03:25:03.989+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-23T03:25:04.016+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): clean_keyword> on 2025-01-22 00:00:00+00:00
[2025-01-23T03:25:04.020+0000] {standard_task_runner.py:57} INFO - Started process 4837 to run task
[2025-01-23T03:25:04.023+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Silver_Layer', 'clean_keyword', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/silver_layer.py', '--cfg-path', '/tmp/tmp0anua54q']
[2025-01-23T03:25:04.026+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask clean_keyword
[2025-01-23T03:25:04.081+0000] {task_command.py:416} INFO - Running <TaskInstance: Silver_Layer.clean_keyword scheduled__2025-01-22T00:00:00+00:00 [running]> on host 73fc507ad5e4
[2025-01-23T03:25:04.232+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Silver_Layer' AIRFLOW_CTX_TASK_ID='clean_keyword' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-23T03:25:04.245+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-01-23T03:25:04.248+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_keyword.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/silver/keywords
[2025-01-23T03:25:04.507+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-01-23T03:25:06.555+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-01-23T03:25:06.764+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-01-23T03:25:06.765+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-01-23T03:25:06.771+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-01-23T03:25:06.772+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-ce26b892-8d91-4099-8fe7-9d33dd886dea;1.0
[2025-01-23T03:25:06.773+0000] {spark_submit.py:579} INFO - confs: [default]
[2025-01-23T03:25:10.431+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 3659ms :: artifacts dl 0ms
[2025-01-23T03:25:10.432+0000] {spark_submit.py:579} INFO - :: modules in use:
[2025-01-23T03:25:10.432+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2025-01-23T03:25:10.433+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2025-01-23T03:25:10.434+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-01-23T03:25:10.434+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2025-01-23T03:25:10.435+0000] {spark_submit.py:579} INFO - |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
[2025-01-23T03:25:10.435+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2025-01-23T03:25:10.436+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.436+0000] {spark_submit.py:579} INFO - :: problems summary ::
[2025-01-23T03:25:10.437+0000] {spark_submit.py:579} INFO - :::: WARNINGS
[2025-01-23T03:25:10.437+0000] {spark_submit.py:579} INFO - problem while downloading module descriptor: https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.pom: Downloaded file size (0) doesn't match expected Content Length (25377) for https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.pom. Please retry. (261ms)
[2025-01-23T03:25:10.438+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.438+0000] {spark_submit.py:579} INFO - module not found: org.apache.hadoop#hadoop-aws;3.3.4
[2025-01-23T03:25:10.439+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.439+0000] {spark_submit.py:579} INFO - ==== local-m2-cache: tried
[2025-01-23T03:25:10.440+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.441+0000] {spark_submit.py:579} INFO - file:/home/***/.m2/repository/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.pom
[2025-01-23T03:25:10.442+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.442+0000] {spark_submit.py:579} INFO - -- artifact org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar:
[2025-01-23T03:25:10.443+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.443+0000] {spark_submit.py:579} INFO - file:/home/***/.m2/repository/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
[2025-01-23T03:25:10.444+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.445+0000] {spark_submit.py:579} INFO - ==== local-ivy-cache: tried
[2025-01-23T03:25:10.446+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.446+0000] {spark_submit.py:579} INFO - /home/***/.ivy2/local/org.apache.hadoop/hadoop-aws/3.3.4/ivys/ivy.xml
[2025-01-23T03:25:10.447+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.447+0000] {spark_submit.py:579} INFO - -- artifact org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar:
[2025-01-23T03:25:10.448+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.449+0000] {spark_submit.py:579} INFO - /home/***/.ivy2/local/org.apache.hadoop/hadoop-aws/3.3.4/jars/hadoop-aws.jar
[2025-01-23T03:25:10.449+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.450+0000] {spark_submit.py:579} INFO - ==== central: tried
[2025-01-23T03:25:10.450+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.451+0000] {spark_submit.py:579} INFO - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.pom
[2025-01-23T03:25:10.451+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.452+0000] {spark_submit.py:579} INFO - ==== spark-packages: tried
[2025-01-23T03:25:10.453+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.453+0000] {spark_submit.py:579} INFO - https://repos.spark-packages.org/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.pom
[2025-01-23T03:25:10.453+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.454+0000] {spark_submit.py:579} INFO - -- artifact org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar:
[2025-01-23T03:25:10.454+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.454+0000] {spark_submit.py:579} INFO - https://repos.spark-packages.org/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
[2025-01-23T03:25:10.454+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.454+0000] {spark_submit.py:579} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-01-23T03:25:10.455+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.455+0000] {spark_submit.py:579} INFO - ::          UNRESOLVED DEPENDENCIES         ::
[2025-01-23T03:25:10.455+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.456+0000] {spark_submit.py:579} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-01-23T03:25:10.456+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.456+0000] {spark_submit.py:579} INFO - :: org.apache.hadoop#hadoop-aws;3.3.4: not found
[2025-01-23T03:25:10.457+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.457+0000] {spark_submit.py:579} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-01-23T03:25:10.458+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.458+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.458+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:25:10.459+0000] {spark_submit.py:579} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-01-23T03:25:10.459+0000] {spark_submit.py:579} INFO - Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: org.apache.hadoop#hadoop-aws;3.3.4: not found]
[2025-01-23T03:25:10.460+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-01-23T03:25:10.460+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-01-23T03:25:10.460+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-01-23T03:25:10.461+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-01-23T03:25:10.461+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-01-23T03:25:10.462+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-01-23T03:25:10.462+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-01-23T03:25:10.462+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-01-23T03:25:10.463+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-01-23T03:25:10.463+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-01-23T03:25:10.480+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_keyword.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/silver/keywords. Error code is: 1.
[2025-01-23T03:25:10.495+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Silver_Layer, task_id=clean_keyword, execution_date=20250122T000000, start_date=20250123T032503, end_date=20250123T032510
[2025-01-23T03:25:10.515+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task clean_keyword (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_keyword.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/silver/keywords. Error code is: 1.; 4837)
[2025-01-23T03:25:10.558+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-23T03:25:10.598+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
