[2025-01-23T03:30:11.098+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Silver_Layer.clean_keyword scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-23T03:30:11.108+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Silver_Layer.clean_keyword scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-23T03:30:11.110+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-23T03:30:11.124+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): clean_keyword> on 2025-01-22 00:00:00+00:00
[2025-01-23T03:30:11.128+0000] {standard_task_runner.py:57} INFO - Started process 6389 to run task
[2025-01-23T03:30:11.131+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Silver_Layer', 'clean_keyword', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/silver_layer.py', '--cfg-path', '/tmp/tmp9b3f0004']
[2025-01-23T03:30:11.134+0000] {standard_task_runner.py:85} INFO - Job 39: Subtask clean_keyword
[2025-01-23T03:30:11.185+0000] {task_command.py:416} INFO - Running <TaskInstance: Silver_Layer.clean_keyword scheduled__2025-01-22T00:00:00+00:00 [running]> on host 73fc507ad5e4
[2025-01-23T03:30:11.267+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Silver_Layer' AIRFLOW_CTX_TASK_ID='clean_keyword' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-23T03:30:11.277+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-01-23T03:30:11.280+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_keyword.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/silver/keywords
[2025-01-23T03:30:11.434+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-01-23T03:30:13.155+0000] {spark_submit.py:579} INFO - 25/01/23 03:30:13 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-23T03:30:14.363+0000] {spark_submit.py:579} INFO - 2025-01-23 03:30:14,362 ERROR: Error initializing Spark session: name 'platform' is not defined
[2025-01-23T03:30:14.371+0000] {spark_submit.py:579} INFO - 2025-01-23 03:30:14,371 ERROR: Traceback (most recent call last):
[2025-01-23T03:30:14.372+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/processing_keyword.py", line 16, in init_spark_session
[2025-01-23T03:30:14.373+0000] {spark_submit.py:579} INFO - logging.info(f"Python version on driver: {platform.python_version()}")
[2025-01-23T03:30:14.373+0000] {spark_submit.py:579} INFO - NameError: name 'platform' is not defined
[2025-01-23T03:30:14.374+0000] {spark_submit.py:579} INFO - 
[2025-01-23T03:30:14.418+0000] {spark_submit.py:579} INFO - 25/01/23 03:30:14 INFO ShutdownHookManager: Shutdown hook called
[2025-01-23T03:30:14.419+0000] {spark_submit.py:579} INFO - 25/01/23 03:30:14 INFO ShutdownHookManager: Deleting directory /tmp/spark-58761c46-eeb0-4b9b-8edb-216eef25e0b2
[2025-01-23T03:30:14.465+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_keyword.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/silver/keywords. Error code is: 1.
[2025-01-23T03:30:14.472+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Silver_Layer, task_id=clean_keyword, execution_date=20250122T000000, start_date=20250123T033011, end_date=20250123T033014
[2025-01-23T03:30:14.473+0000] {silver_layer.py:15} ERROR - Task Silver_Layer__clean_keyword__20250122 failed.
[2025-01-23T03:30:14.488+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 39 for task clean_keyword (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_keyword.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/silver/keywords. Error code is: 1.; 6389)
[2025-01-23T03:30:14.518+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-23T03:30:14.546+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
