[2024-11-02T00:33:16.131+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:33:16.132+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:33:16.134+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:33:16.134+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:33:16.157+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:33:16.151+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:33:16.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:33:16.177+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.049 seconds
[2024-11-02T00:33:46.320+0000] {processor.py:157} INFO - Started process (PID=458) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:33:46.321+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:33:46.323+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:33:46.323+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:33:46.345+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:33:46.340+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:33:46.346+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:33:46.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.048 seconds
[2024-11-02T00:34:16.974+0000] {processor.py:157} INFO - Started process (PID=514) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:34:16.975+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:34:16.976+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:34:16.976+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:34:17.000+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:34:16.993+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:34:17.001+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:34:17.023+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.052 seconds
[2024-11-02T00:34:47.504+0000] {processor.py:157} INFO - Started process (PID=779) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:34:47.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:34:47.506+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:34:47.506+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:34:47.526+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:34:47.521+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:34:47.526+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:34:47.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.047 seconds
[2024-11-02T00:35:18.013+0000] {processor.py:157} INFO - Started process (PID=835) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:35:18.014+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:35:18.016+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:35:18.016+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:35:18.087+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:35:18.053+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:35:18.095+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:35:18.131+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.120 seconds
[2024-11-02T00:35:48.938+0000] {processor.py:157} INFO - Started process (PID=1024) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:35:48.939+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:35:48.943+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:35:48.942+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:35:48.976+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:35:48.968+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:35:48.978+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:35:49.010+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.078 seconds
[2024-11-02T00:36:19.472+0000] {processor.py:157} INFO - Started process (PID=1178) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:36:19.473+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:36:19.475+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:36:19.475+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:36:19.499+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:36:19.493+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:36:19.500+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:36:19.519+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.050 seconds
[2024-11-02T00:36:49.680+0000] {processor.py:157} INFO - Started process (PID=1234) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:36:49.681+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:36:49.683+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:36:49.682+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:36:49.705+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:36:49.700+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:36:49.706+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:36:49.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.049 seconds
[2024-11-02T00:37:20.097+0000] {processor.py:157} INFO - Started process (PID=1290) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:37:20.098+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:37:20.103+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:37:20.102+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:37:20.144+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:37:20.133+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:37:20.146+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:37:20.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.079 seconds
[2024-11-02T00:37:50.514+0000] {processor.py:157} INFO - Started process (PID=1346) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:37:50.514+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:37:50.516+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:37:50.516+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:37:50.535+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:37:50.531+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:37:50.536+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:37:50.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.043 seconds
[2024-11-02T00:38:20.951+0000] {processor.py:157} INFO - Started process (PID=1402) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:38:20.952+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:38:20.954+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:38:20.954+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:38:20.975+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:38:20.970+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:38:20.976+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:38:20.993+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.044 seconds
[2024-11-02T00:38:51.412+0000] {processor.py:157} INFO - Started process (PID=1683) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:38:51.413+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:38:51.414+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:38:51.414+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:38:51.435+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:38:51.430+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:38:51.436+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:38:51.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.090 seconds
[2024-11-02T00:39:21.882+0000] {processor.py:157} INFO - Started process (PID=1739) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:39:21.883+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:39:21.884+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:39:21.884+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:39:21.903+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:39:21.899+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:39:21.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:39:21.923+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.043 seconds
[2024-11-02T00:39:52.315+0000] {processor.py:157} INFO - Started process (PID=2016) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:39:52.316+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:39:52.318+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:39:52.317+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:39:52.339+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:39:52.334+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:39:52.340+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:39:52.359+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.047 seconds
[2024-11-02T00:40:22.625+0000] {processor.py:157} INFO - Started process (PID=2072) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:40:22.626+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:40:22.628+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:40:22.628+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:40:22.648+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:40:22.643+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:40:22.649+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:40:22.666+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.044 seconds
[2024-11-02T00:40:52.933+0000] {processor.py:157} INFO - Started process (PID=2128) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:40:52.934+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:40:52.936+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:40:52.936+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:40:52.957+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:40:52.953+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:40:52.959+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:40:52.977+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.047 seconds
[2024-11-02T00:41:23.345+0000] {processor.py:157} INFO - Started process (PID=2400) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:41:23.345+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:41:23.348+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:41:23.347+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:41:23.367+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:41:23.362+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:41:23.368+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:41:23.389+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.047 seconds
[2024-11-02T00:41:53.792+0000] {processor.py:157} INFO - Started process (PID=2456) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:41:53.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:41:53.794+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:41:53.794+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:41:53.813+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:41:53.809+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:41:53.815+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:41:53.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.043 seconds
[2024-11-02T00:42:24.039+0000] {processor.py:157} INFO - Started process (PID=2512) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:42:24.040+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:42:24.042+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:42:24.042+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:42:24.061+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:42:24.056+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:42:24.062+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:42:24.080+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.044 seconds
[2024-11-02T00:42:54.295+0000] {processor.py:157} INFO - Started process (PID=2568) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:42:54.296+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:42:54.298+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:42:54.297+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:42:54.317+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:42:54.313+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:42:54.318+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:42:54.335+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.043 seconds
[2024-11-02T00:43:24.845+0000] {processor.py:157} INFO - Started process (PID=2624) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:43:24.846+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:43:24.849+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:43:24.849+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:43:24.871+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:43:24.866+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:43:24.872+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:43:24.889+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.047 seconds
[2024-11-02T00:43:55.265+0000] {processor.py:157} INFO - Started process (PID=2680) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:43:55.266+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:43:55.267+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:43:55.267+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:43:55.287+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:43:55.282+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:43:55.288+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:43:55.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.043 seconds
[2024-11-02T00:44:25.576+0000] {processor.py:157} INFO - Started process (PID=2736) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:44:25.577+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:44:25.579+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:44:25.579+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:44:25.601+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:44:25.596+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:44:25.602+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:44:25.621+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.048 seconds
[2024-11-02T00:44:56.209+0000] {processor.py:157} INFO - Started process (PID=2875) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:44:56.210+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:44:56.212+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:44:56.212+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:44:56.234+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:44:56.228+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:44:56.235+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:44:56.258+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.052 seconds
[2024-11-02T00:45:26.525+0000] {processor.py:157} INFO - Started process (PID=3062) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:45:26.526+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:45:26.529+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:45:26.528+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:45:26.556+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:45:26.548+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:45:26.557+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:45:26.581+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.059 seconds
[2024-11-02T00:45:56.658+0000] {processor.py:157} INFO - Started process (PID=3118) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:45:56.659+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:45:56.661+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:45:56.661+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:45:56.681+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:45:56.676+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:45:56.682+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:45:56.700+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.044 seconds
[2024-11-02T00:46:27.014+0000] {processor.py:157} INFO - Started process (PID=3174) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:46:27.015+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:46:27.016+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:46:27.016+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:46:27.036+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:46:27.032+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:46:27.037+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:46:27.057+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.046 seconds
[2024-11-02T00:46:57.434+0000] {processor.py:157} INFO - Started process (PID=3230) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:46:57.435+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:46:57.437+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:46:57.437+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:46:57.459+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:46:57.455+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:46:57.461+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:46:57.484+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.053 seconds
[2024-11-02T00:47:27.858+0000] {processor.py:157} INFO - Started process (PID=3286) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:47:27.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:47:27.861+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:47:27.861+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:47:27.881+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:47:27.876+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:47:27.882+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:47:27.901+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.045 seconds
[2024-11-02T00:47:58.155+0000] {processor.py:157} INFO - Started process (PID=3342) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:47:58.156+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:47:58.158+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:47:58.158+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:47:58.181+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:47:58.176+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:47:58.182+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:47:58.201+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.049 seconds
[2024-11-02T00:48:28.475+0000] {processor.py:157} INFO - Started process (PID=3398) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:48:28.476+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:48:28.478+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:48:28.478+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:48:28.497+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:48:28.493+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:48:28.498+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:48:28.516+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.044 seconds
[2024-11-02T00:48:58.954+0000] {processor.py:157} INFO - Started process (PID=3454) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:48:58.955+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:48:58.957+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:48:58.957+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:48:58.976+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:48:58.972+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:48:58.977+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:48:58.996+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.044 seconds
[2024-11-02T00:49:29.398+0000] {processor.py:157} INFO - Started process (PID=3510) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:49:29.399+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:49:29.400+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:49:29.400+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:49:29.420+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:49:29.416+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:49:29.421+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:49:29.439+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.044 seconds
[2024-11-02T00:49:59.673+0000] {processor.py:157} INFO - Started process (PID=3566) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:49:59.674+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:49:59.676+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:49:59.676+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:49:59.700+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:49:59.696+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:49:59.702+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:49:59.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.051 seconds
[2024-11-02T00:50:29.794+0000] {processor.py:157} INFO - Started process (PID=3835) to work on /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:50:29.795+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/hjjjjj.py for tasks to queue
[2024-11-02T00:50:29.797+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:50:29.797+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:50:29.827+0000] {logging_mixin.py:151} INFO - [2024-11-02T00:50:29.819+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/hjjjjj.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/hjjjjj.py", line 95, in <module>
    merger_data = SparkSubmitOperator(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 137, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/task_group.py", line 230, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'clean_movies' has already been added to the DAG
[2024-11-02T00:50:29.828+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/hjjjjj.py
[2024-11-02T00:50:29.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/hjjjjj.py took 0.068 seconds
