[2024-11-03T09:26:52.457+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clean_keyyyyyy.clean_keyword manual__2024-11-03T09:26:50.613441+00:00 [queued]>
[2024-11-03T09:26:52.470+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clean_keyyyyyy.clean_keyword manual__2024-11-03T09:26:50.613441+00:00 [queued]>
[2024-11-03T09:26:52.471+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-11-03T09:26:52.489+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): clean_keyword> on 2024-11-03 09:26:50.613441+00:00
[2024-11-03T09:26:52.495+0000] {standard_task_runner.py:57} INFO - Started process 1221 to run task
[2024-11-03T09:26:52.499+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'clean_keyyyyyy', 'clean_keyword', 'manual__2024-11-03T09:26:50.613441+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/cleaned_key.py', '--cfg-path', '/tmp/tmpzv3h24us']
[2024-11-03T09:26:52.511+0000] {standard_task_runner.py:85} INFO - Job 144: Subtask clean_keyword
[2024-11-03T09:26:52.627+0000] {task_command.py:415} INFO - Running <TaskInstance: clean_keyyyyyy.clean_keyword manual__2024-11-03T09:26:50.613441+00:00 [running]> on host 014143abc908
[2024-11-03T09:26:52.747+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='clean_keyyyyyy' AIRFLOW_CTX_TASK_ID='clean_keyword' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T09:26:50.613441+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T09:26:50.613441+00:00'
[2024-11-03T09:26:52.760+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-11-03T09:26:52.762+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.4.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/test_Key.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/sliver/keywords
[2024-11-03T09:26:52.879+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-11-03T09:26:56.529+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-11-03T09:26:56.762+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2024-11-03T09:26:56.764+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2024-11-03T09:26:56.781+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-11-03T09:26:56.783+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-feea0a67-a24a-4632-9556-f762c38aa6b4;1.0
[2024-11-03T09:26:56.784+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-11-03T09:27:02.107+0000] {spark_submit.py:579} INFO - found org.apache.hadoop#hadoop-aws;3.3.4 in central
[2024-11-03T09:27:03.917+0000] {spark_submit.py:579} INFO - found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2024-11-03T09:27:06.859+0000] {spark_submit.py:579} INFO - found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-11-03T09:27:07.218+0000] {spark_submit.py:579} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar ...
[2024-11-03T09:27:07.674+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-11-03T09:27:07.678+0000] {process_utils.py:131} INFO - Sending 15 to group 1221. PIDs of all processes in the group: [1224, 1221]
[2024-11-03T09:27:07.678+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1221
[2024-11-03T09:27:07.679+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-03T09:27:07.680+0000] {spark_submit.py:705} INFO - Sending kill signal to spark-submit
[2024-11-03T09:27:07.732+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1224, status='terminated', started='09:26:52') (1224) terminated with exit code None
[2024-11-03T09:27:07.733+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1221, status='terminated', exitcode=0, started='09:26:52') (1221) terminated with exit code 0
