[2024-12-16T14:17:37.324+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: All_Layer.clean_keyword manual__2024-12-16T14:17:20.331942+00:00 [queued]>
[2024-12-16T14:17:37.345+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: All_Layer.clean_keyword manual__2024-12-16T14:17:20.331942+00:00 [queued]>
[2024-12-16T14:17:37.346+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-16T14:17:37.368+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): clean_keyword> on 2024-12-16 14:17:20.331942+00:00
[2024-12-16T14:17:37.380+0000] {standard_task_runner.py:57} INFO - Started process 663 to run task
[2024-12-16T14:17:37.387+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'All_Layer', 'clean_keyword', 'manual__2024-12-16T14:17:20.331942+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/All_Offi.py', '--cfg-path', '/tmp/tmph73jkymf']
[2024-12-16T14:17:37.391+0000] {standard_task_runner.py:85} INFO - Job 216: Subtask clean_keyword
[2024-12-16T14:17:37.472+0000] {task_command.py:416} INFO - Running <TaskInstance: All_Layer.clean_keyword manual__2024-12-16T14:17:20.331942+00:00 [running]> on host a2b73f6a4b3a
[2024-12-16T14:17:37.599+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='All_Layer' AIRFLOW_CTX_TASK_ID='clean_keyword' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T14:17:20.331942+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T14:17:20.331942+00:00'
[2024-12-16T14:17:37.614+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2024-12-16T14:17:37.617+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --jars /opt/***/jars/hadoop-aws-3.3.4.jar,/opt/***/jars/s3-2.18.41.jar,/opt/***/jars/aws-java-sdk-1.12.367.jar,/opt/***/jars/delta-core_2.12-2.2.0.jar,/opt/***/jars/delta-storage-2.2.0.jar, --packages org.apache.hadoop:hadoop-aws:3.3.4 --num-executors 2 --total-executor-cores 2 --executor-cores 2 --executor-memory 1g --driver-memory 1g --name arrow-spark --deploy-mode client /opt/***/jobs/python/processing_keyword.py s3a://lakehouse/bronze/keywords.parquet s3a://lakehouse/sliver/keywords
[2024-12-16T14:17:37.957+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-12-16T14:17:43.506+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-12-16T14:17:43.858+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2024-12-16T14:17:43.860+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2024-12-16T14:17:43.906+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-12-16T14:17:43.917+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-3491e31e-00b3-4f2d-976b-71495e9bcebd;1.0
[2024-12-16T14:17:43.946+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-12-16T14:17:44.402+0000] {spark_submit.py:579} INFO - found org.apache.hadoop#hadoop-aws;3.3.4 in spark-list
[2024-12-16T14:17:44.494+0000] {spark_submit.py:579} INFO - found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2024-12-16T14:17:44.596+0000] {spark_submit.py:579} INFO - found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in spark-list
[2024-12-16T14:17:44.701+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 756ms :: artifacts dl 29ms
[2024-12-16T14:17:44.702+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-12-16T14:17:44.703+0000] {spark_submit.py:579} INFO - com.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]
[2024-12-16T14:17:44.704+0000] {spark_submit.py:579} INFO - org.apache.hadoop#hadoop-aws;3.3.4 from spark-list in [default]
[2024-12-16T14:17:44.705+0000] {spark_submit.py:579} INFO - org.wildfly.openssl#wildfly-openssl;1.0.7.Final from spark-list in [default]
[2024-12-16T14:17:44.705+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-12-16T14:17:44.705+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-12-16T14:17:44.706+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-12-16T14:17:44.708+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-12-16T14:17:44.708+0000] {spark_submit.py:579} INFO - |      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-12-16T14:17:44.710+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-12-16T14:17:44.719+0000] {spark_submit.py:579} INFO - 
[2024-12-16T14:17:44.720+0000] {spark_submit.py:579} INFO - :: problems summary ::
[2024-12-16T14:17:44.721+0000] {spark_submit.py:579} INFO - :::: ERRORS
[2024-12-16T14:17:44.722+0000] {spark_submit.py:579} INFO - unknown resolver null
[2024-12-16T14:17:44.723+0000] {spark_submit.py:579} INFO - 
[2024-12-16T14:17:44.723+0000] {spark_submit.py:579} INFO - unknown resolver null
[2024-12-16T14:17:44.724+0000] {spark_submit.py:579} INFO - 
[2024-12-16T14:17:44.724+0000] {spark_submit.py:579} INFO - 
[2024-12-16T14:17:44.725+0000] {spark_submit.py:579} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2024-12-16T14:17:44.725+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-3491e31e-00b3-4f2d-976b-71495e9bcebd
[2024-12-16T14:17:44.725+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-12-16T14:17:44.758+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 3 already retrieved (0kB/47ms)
[2024-12-16T14:17:45.617+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-12-16T14:17:47.786+0000] {spark_submit.py:579} INFO - 2024-12-16 14:17:47,786 INFO: Initializing Spark session...
[2024-12-16T14:17:48.109+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SparkContext: Running Spark version 3.3.2
[2024-12-16T14:17:48.164+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceUtils: ==============================================================
[2024-12-16T14:17:48.166+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-12-16T14:17:48.167+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceUtils: ==============================================================
[2024-12-16T14:17:48.169+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SparkContext: Submitted application: CleanKeywords
[2024-12-16T14:17:48.232+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 2, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-12-16T14:17:48.272+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceProfile: Limiting resource is cpus at 2 tasks per executor
[2024-12-16T14:17:48.276+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-12-16T14:17:48.405+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SecurityManager: Changing view acls to: ***
[2024-12-16T14:17:48.405+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SecurityManager: Changing modify acls to: ***
[2024-12-16T14:17:48.407+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SecurityManager: Changing view acls groups to:
[2024-12-16T14:17:48.408+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SecurityManager: Changing modify acls groups to:
[2024-12-16T14:17:48.408+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:48 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2024-12-16T14:17:49.310+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO Utils: Successfully started service 'sparkDriver' on port 46791.
[2024-12-16T14:17:49.368+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO SparkEnv: Registering MapOutputTracker
[2024-12-16T14:17:49.432+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO SparkEnv: Registering BlockManagerMaster
[2024-12-16T14:17:49.477+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-12-16T14:17:49.479+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-12-16T14:17:49.485+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-12-16T14:17:49.574+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0e8f687b-2638-4086-965d-0b8733d36fa8
[2024-12-16T14:17:49.617+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-12-16T14:17:49.656+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:49 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-12-16T14:17:50.041+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-12-16T14:17:50.044+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-12-16T14:17:50.054+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO Utils: Successfully started service 'SparkUI' on port 4042.
[2024-12-16T14:17:50.154+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///opt/***/jars/hadoop-aws-3.3.4.jar at spark://a2b73f6a4b3a:46791/jars/hadoop-aws-3.3.4.jar with timestamp 1734358668086
[2024-12-16T14:17:50.156+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///opt/***/jars/s3-2.18.41.jar at spark://a2b73f6a4b3a:46791/jars/s3-2.18.41.jar with timestamp 1734358668086
[2024-12-16T14:17:50.163+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///opt/***/jars/aws-java-sdk-1.12.367.jar at spark://a2b73f6a4b3a:46791/jars/aws-java-sdk-1.12.367.jar with timestamp 1734358668086
[2024-12-16T14:17:50.167+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///opt/***/jars/delta-core_2.12-2.2.0.jar at spark://a2b73f6a4b3a:46791/jars/delta-core_2.12-2.2.0.jar with timestamp 1734358668086
[2024-12-16T14:17:50.170+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///opt/***/jars/delta-storage-2.2.0.jar at spark://a2b73f6a4b3a:46791/jars/delta-storage-2.2.0.jar with timestamp 1734358668086
[2024-12-16T14:17:50.171+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar at spark://a2b73f6a4b3a:46791/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar with timestamp 1734358668086
[2024-12-16T14:17:50.172+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar at spark://a2b73f6a4b3a:46791/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar with timestamp 1734358668086
[2024-12-16T14:17:50.174+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar at spark://a2b73f6a4b3a:46791/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar with timestamp 1734358668086
[2024-12-16T14:17:50.178+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar at spark://a2b73f6a4b3a:46791/files/org.apache.hadoop_hadoop-aws-3.3.4.jar with timestamp 1734358668086
[2024-12-16T14:17:50.181+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar to /tmp/spark-1b4419f2-9362-498c-b4a1-9b2e92b8a9ef/userFiles-7d2f2dba-a4bc-4145-8729-b50ce915eaca/org.apache.hadoop_hadoop-aws-3.3.4.jar
[2024-12-16T14:17:50.214+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO SparkContext: Added file file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar at spark://a2b73f6a4b3a:46791/files/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar with timestamp 1734358668086
[2024-12-16T14:17:50.216+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:50 INFO Utils: Copying /home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar to /tmp/spark-1b4419f2-9362-498c-b4a1-9b2e92b8a9ef/userFiles-7d2f2dba-a4bc-4145-8729-b50ce915eaca/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar
[2024-12-16T14:17:52.330+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:52 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar at spark://a2b73f6a4b3a:46791/files/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar with timestamp 1734358668086
[2024-12-16T14:17:52.331+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:52 INFO Utils: Copying /home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar to /tmp/spark-1b4419f2-9362-498c-b4a1-9b2e92b8a9ef/userFiles-7d2f2dba-a4bc-4145-8729-b50ce915eaca/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar
[2024-12-16T14:17:52.599+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:52 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-12-16T14:17:52.698+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:52 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.5:7077 after 54 ms (0 ms spent in bootstraps)
[2024-12-16T14:17:54.061+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241216141754-0001
[2024-12-16T14:17:54.082+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38247.
[2024-12-16T14:17:54.083+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO NettyBlockTransferService: Server created on a2b73f6a4b3a:38247
[2024-12-16T14:17:54.086+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-12-16T14:17:54.100+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, a2b73f6a4b3a, 38247, None)
[2024-12-16T14:17:54.107+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO BlockManagerMasterEndpoint: Registering block manager a2b73f6a4b3a:38247 with 434.4 MiB RAM, BlockManagerId(driver, a2b73f6a4b3a, 38247, None)
[2024-12-16T14:17:54.111+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, a2b73f6a4b3a, 38247, None)
[2024-12-16T14:17:54.113+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, a2b73f6a4b3a, 38247, None)
[2024-12-16T14:17:54.622+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:54 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-12-16T14:17:55.017+0000] {spark_submit.py:579} INFO - 2024-12-16 14:17:55,016 INFO: Spark session initialized successfully.
[2024-12-16T14:17:55.020+0000] {spark_submit.py:579} INFO - 2024-12-16 14:17:55,016 INFO: Reading data from s3a://lakehouse/bronze/keywords.parquet
[2024-12-16T14:17:55.031+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:55 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-12-16T14:17:55.350+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:55 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2024-12-16T14:17:55.379+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:55 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2024-12-16T14:17:55.380+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:55 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2024-12-16T14:17:57.792+0000] {spark_submit.py:579} INFO - 24/12/16 14:17:57 INFO SharedState: Warehouse path is 's3a://lakehouse/'.
[2024-12-16T14:18:00.828+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:00 INFO InMemoryFileIndex: It took 212 ms to list leaf files for 1 paths.
[2024-12-16T14:18:01.908+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:01 INFO SparkContext: Starting job: load at NativeMethodAccessorImpl.java:0
[2024-12-16T14:18:01.942+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:01 INFO DAGScheduler: Got job 0 (load at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2024-12-16T14:18:01.943+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:01 INFO DAGScheduler: Final stage: ResultStage 0 (load at NativeMethodAccessorImpl.java:0)
[2024-12-16T14:18:01.949+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:01 INFO DAGScheduler: Parents of final stage: List()
[2024-12-16T14:18:01.954+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:01 INFO DAGScheduler: Missing parents: List()
[2024-12-16T14:18:01.983+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:01 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at load at NativeMethodAccessorImpl.java:0), which has no missing parents
[2024-12-16T14:18:02.124+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:02 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 106.2 KiB, free 434.3 MiB)
[2024-12-16T14:18:02.180+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:02 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 38.4 KiB, free 434.3 MiB)
[2024-12-16T14:18:02.186+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:02 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on a2b73f6a4b3a:38247 (size: 38.4 KiB, free: 434.4 MiB)
[2024-12-16T14:18:02.195+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:02 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1513
[2024-12-16T14:18:02.228+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:02 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at load at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2024-12-16T14:18:02.230+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:02 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2024-12-16T14:18:17.266+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:17 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:18:32.266+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:32 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:18:47.265+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:47 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:19:00.025+0000] {spark_submit.py:579} INFO - 24/12/16 14:18:59 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241216141754-0001/0 on worker-20241216141212-172.18.0.9-45515 (172.18.0.9:45515) with 2 core(s)
[2024-12-16T14:19:00.035+0000] {spark_submit.py:579} INFO - 24/12/16 14:19:00 INFO StandaloneSchedulerBackend: Granted executor ID app-20241216141754-0001/0 on hostPort 172.18.0.9:45515 with 2 core(s), 1024.0 MiB RAM
[2024-12-16T14:19:00.280+0000] {spark_submit.py:579} INFO - 24/12/16 14:19:00 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241216141754-0001/0 is now RUNNING
[2024-12-16T14:19:02.269+0000] {spark_submit.py:579} INFO - 24/12/16 14:19:02 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-12-16T14:19:04.209+0000] {spark_submit.py:579} INFO - 24/12/16 14:19:04 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.9:56918) with ID 0,  ResourceProfileId 0
[2024-12-16T14:19:04.307+0000] {spark_submit.py:579} INFO - 24/12/16 14:19:04 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.9:39649 with 434.4 MiB RAM, BlockManagerId(0, 172.18.0.9, 39649, None)
[2024-12-16T14:19:24.294+0000] {spark_submit.py:579} INFO - 24/12/16 14:19:24 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@7691dee)) by listener AppStatusListener took 1.243864746s.
[2024-12-16T14:19:22.619+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-12-16T14:20:03.784+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-12-16T14:20:07.777+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:07 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.18.0.9, executor 0, partition 0, PROCESS_LOCAL, 4591 bytes) taskResourceAssignments Map()
[2024-12-16T14:20:08.262+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:08 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.18.0.9:39649 (size: 38.4 KiB, free: 434.4 MiB)
[2024-12-16T14:20:11.139+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:11 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 3389 ms on 172.18.0.9 (executor 0) (1/1)
[2024-12-16T14:20:11.144+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:11 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2024-12-16T14:20:11.158+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:11 INFO DAGScheduler: ResultStage 0 (load at NativeMethodAccessorImpl.java:0) finished in 129.142 s
[2024-12-16T14:20:11.163+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:11 INFO DAGScheduler: Job 0 is finished. Cancelling potential speculative or zombie tasks for this job
[2024-12-16T14:20:11.165+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:11 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage finished
[2024-12-16T14:20:11.168+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:11 INFO DAGScheduler: Job 0 finished: load at NativeMethodAccessorImpl.java:0, took 128.661552 s
[2024-12-16T14:20:11.956+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:11 INFO BlockManagerInfo: Removed broadcast_0_piece0 on 172.18.0.9:39649 in memory (size: 38.4 KiB, free: 434.4 MiB)
[2024-12-16T14:20:11.963+0000] {spark_submit.py:579} INFO - 24/12/16 14:20:11 INFO BlockManagerInfo: Removed broadcast_0_piece0 on a2b73f6a4b3a:38247 in memory (size: 38.4 KiB, free: 434.4 MiB)
[2024-12-16T14:20:14.304+0000] {spark_submit.py:579} INFO - 2024-12-16 14:20:14,303 INFO: Cleaning data...
[2024-12-16T14:20:14.535+0000] {spark_submit.py:579} INFO - 2024-12-16 14:20:14,534 INFO: Data cleaned and transformed.
[2024-12-16T14:20:14.535+0000] {spark_submit.py:579} INFO - 2024-12-16 14:20:14,534 INFO: Saving cleaned data to s3a://lakehouse/sliver/keywords
[2024-12-16T14:20:14.639+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-16T14:20:14.651+0000] {process_utils.py:131} INFO - Sending 15 to group 663. PIDs of all processes in the group: [669, 964, 663]
[2024-12-16T14:20:14.664+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 663
[2024-12-16T14:20:14.670+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-16T14:20:14.676+0000] {spark_submit.py:705} INFO - Sending kill signal to spark-submit
[2024-12-16T14:20:14.732+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 493, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 542, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-16T14:20:14.789+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=All_Layer, task_id=clean_keyword, execution_date=20241216T141720, start_date=20241216T141737, end_date=20241216T142014
[2024-12-16T14:20:15.014+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 216 for task clean_keyword (Task received SIGTERM signal; 663)
[2024-12-16T14:20:15.107+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=669, status='terminated', started='14:17:37') (669) terminated with exit code None
[2024-12-16T14:20:15.115+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=964, status='terminated', started='14:17:46') (964) terminated with exit code None
[2024-12-16T14:20:15.117+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=663, status='terminated', exitcode=1, started='14:17:37') (663) terminated with exit code 1
